### ISSUE TITLE
Issue 1: User can view a list of all villagers

### ISSUE THREAD

**Issue by moniquechang** [moniquechang/ACNH-Villagers#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of all villagers of the game Animal Crossing 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can scroll down to see all villagers (including name and pic) 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="648" alt="feature-1 mobile desktop" src="https://user-images.githubusercontent.com/103399595/183218267-d35d1539-a5f6-45d8-b602-aebfb816027f.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] format html and css for both mobile and desktop screens
- [x] create background card/polaroid template that will hold each villager's name and picture (test w/ dummy entries)
- [x] request data for all villagers' information from ACNH API 
- [x] create data model to hold data from request
- [x] store data from API 
- [x] create li elements that match that of the dummy entries (DOM tree creation)
- [x] add function that will render DOM tree for every villager using data from API
- **Clean Up**
  - [x] Remove all console logs, commented out code, etc
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
