### ISSUE TITLE
Issue 2: User can search for villagers by name

### ISSUE THREAD

**Issue by moniquechang** [moniquechang/ACNH-Villagers#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for specific villagers by name

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can use search bar to type name of villager they are looking for in order to find them more quickly

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="613" alt="feature-2 mobile" src="https://user-images.githubusercontent.com/103399595/183218504-50d7a6ca-4987-48fa-ab1d-1d6b47107c6f.png">

<img width="866" alt="feature-2 desktop-1" src="https://user-images.githubusercontent.com/103399595/183218514-1bb2846f-b710-4b70-82cf-311d613a55b2.png">
<img width="877" alt="feature-2 desktop-2" src="https://user-images.githubusercontent.com/103399595/183218520-fe39cd55-fdfc-426b-816d-380a4ab1f65f.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] configure html and css to add search bar for both mobile and desktop screens
- [x] create default text to show when search entry does not match the name of any villager
- [x] add event handler function to hide all villagers except for the villager w/ the name the user types in search bar
- [x] adjust function to account for lowercase and uppercase entries
- [x] add function to show default text if search entry does not match any villager names
- [x] add event handler function to show all villagers again if search bar is empty
- **Clean Up**
  - [x] Remove all console logs, commented out code etc
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
