### ISSUE TITLE
Issue 3: User can click each villager to see more in depth information about them

### ISSUE THREAD

**Issue by moniquechang** [moniquechang/ACNH-Villagers#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view more in depth information about each villager

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click a villager's name to see a popup window of more specific information about that villager

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="507" alt="feature-3 mobile" src="https://user-images.githubusercontent.com/103399595/183218725-60be50ea-4c4a-41ff-bcfa-c8635938d017.png">

<img width="881" alt="feature-3 desktop-1" src="https://user-images.githubusercontent.com/103399595/183218735-a5987d2a-8129-41b5-ab6b-c4b31c6739c4.png">
<img width="452" alt="feature-3 desktop-2" src="https://user-images.githubusercontent.com/103399595/183218752-a43c70ad-587d-4f49-9d94-df98f3bf6332.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add pseudo class to name text of villagers to underline name when mouse is hovered
- [x] make modal to show more in depth information when name is clicked (dummy entry)
- [x] add click event handler to show modal when name is clicked
- [x] add function to hide modal when close button is clicked on modal
- [x] use data from API to fill modal window with information about villager (DOM creation)
- **Clean Up**
  - [x] Remove all console logs, commented out code, etc
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
