### ISSUE TITLE
Issue 4: User can save their favorite villagers to a favorites list

### ISSUE THREAD

**Issue by moniquechang** [moniquechang/ACNH-Villagers#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save villagers to a favorites list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click an icon next to the villager's name to add that villager to a separate favorites list

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="477" alt="feature-4 mobile" src="https://user-images.githubusercontent.com/103399595/183219009-b1ab4188-f041-4180-bcf2-c378015fccfa.png">

<img width="873" alt="feature-4 desktop-1" src="https://user-images.githubusercontent.com/103399595/183219018-82cb1094-b526-42c5-95a1-478e879357c8.png">
<img width="453" alt="feature-4 desktop-2" src="https://user-images.githubusercontent.com/103399595/183219023-fe51c6d8-6ab3-4985-8987-1f9559fc1459.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add hollow heart icon next to villager names in renderVillager function
- [x] create confirmation modal with 'yes' and 'no' buttons
- [x] add click event handler to heart icon to show confirmation modal when icon is clicked
- [x] add event handler to close modal when "no" button is clicked
- [x] add event handler to 'yes' button to close modal and change hollow heart icon into solid heart icon
- [x] add event handler to 'yes' button to save villager info in data model
- [x] save data model to local storage
- **Clean Up**
  - [x] Remove all console logs, commented out code, etc
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
