### ISSUE TITLE
Issue 5: User can view favorites list

### ISSUE THREAD

**Issue by moniquechang** [moniquechang/ACNH-Villagers#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their favorites list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click a link in the navigation bar that will show their list of villagers they saved

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="530" alt="feature-5 mobile" src="https://user-images.githubusercontent.com/103399595/183219168-758e3fba-503e-4987-bd5a-8786adca70f3.png">

<img width="857" alt="feature-5 desktop-1" src="https://user-images.githubusercontent.com/103399595/183219179-b66849e3-6522-4c91-ad3d-4b2304af580a.png">
<img width="470" alt="feature-5 desktop-2" src="https://user-images.githubusercontent.com/103399595/183219191-7050f5fa-5ac4-49c4-ae1d-ad884ba54401.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] make sure once a villager is saved, the heart icon stays solid even after refreshing page 
- [x] add data-view attributes 
- [x] create favorites list view
- [x] add link to favorites list in nav bar
- [x] make "acnh villagers" a link to go to villagers view
- [x] create function to view swap
- [x] render DOM tree for villagers that were favorited
- [x] make sure favorited villagers are shown on favorites view when page is refreshed
- [x] show default text if no villagers were saved
- [x] add function to show same view when page is refreshed
- **Clean Up**
  - [x] Remove all console logs, commented out code, etc
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
